name: CI/CD Pipeline

on:
  push:
    branches:
      - master

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      run: npm install

    # - name: Run tests
    #   run: npm test

    - name: Edit HTML
      run: npm run editHTML  # This will run your editHTML.js script

    - name: Minify js files
      run: npm run build

    - name: Deploy to Heroku
      uses: AkhileshNS/heroku-deploy@v3.13.15  # Use the latest version
      with:
        heroku_api_key: ${{secrets.HEROKU_API_KEY}}
        heroku_app_name: timekeeper-pro  # Replace with your app's name
        heroku_email: ${{secrets.EMAIL}}  # Replace with your Heroku account email